# Generated by Django 5.1.4 on 2024-12-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_route_remove_booking_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
