# Generated by Django 5.1.4 on 2024-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_route_base_price_alter_route_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
