# Generated by Django 5.1.4 on 2024-12-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
