# Generated by Django 5.2.17 on 2026-09-10 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0007_delete_legacy_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=16, unique=True)),
                ('kind', models.CharField(choices=[('BRTS', 'BRTS iBus'), ('CITY', 'City Bus')], default='CITY', max_length=8)),
                ('total_seats', models.PositiveSmallIntegerField(default=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'buses',
                'ordering': ['registration'],
            },
        ),
        migrations.CreateModel(
            name='FareSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_km', models.DecimalField(decimal_places=2, help_text='Inclusive', max_digits=5)),
                ('max_km', models.DecimalField(blank=True, decimal_places=2, help_text='Exclusive. Leave empty for the open-ended top slab.', max_digits=5, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['min_km'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(db_index=True, max_length=20)),
                ('direction', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], max_length=3)),
                ('body', models.TextField(blank=True)),
                ('twilio_sid', models.CharField(blank=True, db_index=True, max_length=48)),
                ('state_before', models.CharField(blank=True, max_length=32)),
                ('state_after', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('BRTS', 'BRTS iBus'), ('CITY', 'City Bus')], default='CITY', max_length=8)),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], default='UP', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. VJN', max_length=8, unique=True)),
                ('norm_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(editable=False, max_length=10, unique=True)),
                ('whatsapp_number', models.CharField(db_index=True, max_length=20)),
                ('origin_sequence', models.PositiveSmallIntegerField(default=0)),
                ('destination_sequence', models.PositiveSmallIntegerField(default=0)),
                ('board_at', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fare_per_seat', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('seat_count', models.PositiveSmallIntegerField(default=1)),
                ('total_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('WEB', 'Web'), ('API', 'API')], default='WHATSAPP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bot.booking')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(help_text='E.164', max_length=20, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(max_length=20, unique=True)),
                ('state', models.CharField(db_index=True, default='IDLE', max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('history', models.JSONField(blank=True, default=list)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.passengerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bot.passengerprofile'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Pay on bus'), ('UPI', 'UPI'), ('MOCK', 'Mock')], default='MOCK', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bot.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('days_of_week', models.CharField(default='1111111', help_text='Mon..Sun, 1 = runs. e.g. 1111100', max_length=7)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bot.route')),
            ],
            options={
                'ordering': ['route', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('distance_from_origin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('offset_minutes', models.PositiveSmallIntegerField(default=0, help_text='Minutes after trip departure that the bus reaches this stop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='bot.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='bot.stop')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(related_name='routes', through='bot.RouteStop', to='bot.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bot.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bot.stop'),
        ),
        migrations.CreateModel(
            name='StopAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('norm_alias', models.CharField(blank=True, db_index=True, max_length=100)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='bot.stop')),
            ],
            options={
                'verbose_name_plural': 'stop aliases',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('departure_datetime', models.DateTimeField()),
                ('total_seats', models.PositiveSmallIntegerField(default=32)),
                ('seats_booked', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DEPARTED', 'Departed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='bot.route')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.schedule')),
            ],
            options={
                'ordering': ['departure_datetime'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bot.trip'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('route', 'departure_time', 'valid_from'), name='uniq_schedule'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['stop', 'route'], name='ix_routestop_stop_route'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='uniq_route_seq'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'stop'), name='uniq_route_stop'),
        ),
        migrations.AddConstraint(
            model_name='stopalias',
            constraint=models.UniqueConstraint(fields=('norm_alias',), name='uniq_norm_alias'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route', 'departure_datetime', 'status'], name='ix_trip_lookup'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['service_date'], name='ix_trip_date'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('schedule', 'service_date'), name='uniq_trip_per_day'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('seats_booked__lte', models.F('total_seats'))), name='ck_no_oversell'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['whatsapp_number', '-created_at'], name='ix_bk_wa_recent'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['trip', 'status'], name='ix_bk_trip_status'),
        ),
    ]
